version: "2"

services:
  mongo:
    build: ./mongo
    networks:
      - proxy
    volumes:
      - ./data:/data/db

  node:
    build: ./node
    volumes:
      - ./:/usr/src/app
    expose:
      - 3000
    networks:
      - proxy
    user: "1000:1000"
    command: sh -c "npm install && npm run start"

networks:
  proxy:
    external: true
