version: "2"

services:

  mongo:
      image: mongo
      volumes:
          - ./data:/data/db

  node:
    build: .
    volumes:
      - ./:/usr/src/app
    expose:
      - 3000
    user: "1000:1000"
    command: sh -c "npm install && npm run start"

networks:
    default:
        external:
            name: nginx-reverse-proxy_default
